### ISSUE TITLE
Support for Google Chrome

### ISSUE THREAD

**Issue by Satvik-B** [agrawal-d/cph-submit#4]
Are there any chances of getting support for google chrome for submissions directly?
Is there any help required, we have a big community that can help you in finishing the project.

Also if you have an alternative for submissions automatically, please tell me. The tool CPH is very helpful.

**Comment by sxmeer-ahmed** [comment]
+1 can u make it available for google chrome?

**Comment by VedantValsangkar** [comment]
Still Looking for chrome

**Comment by shahria7k** [comment]
> +1 can u make it available for google chrome?

I am working on it.

**Comment by shahria7k** [comment]
A pr is hanging. I guess #https://github.com/abdallamaher/cph-submit is the solution.

**Comment by urparvezali** [comment]
really need this for chromium based browsers

**Comment by urparvezali** [comment]
I use it for chrome since long time but from some days it show some errors. Please do help to solve this. the errors are shown below,
`> cph-submit@1.0.0 webpack
> webpack --mode=production

assets by status 17.4 KiB [cached] 2 assets
orphan modules 5.51 KiB [orphan] 3 modules
cacheable modules 11.3 KiB
  ./src/backgroundScript.ts + 3 modules 9.59 KiB [built] [code generated]
  ./src/injectedScript.ts + 2 modules 1.7 KiB [built] [code generated]

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1485,42)
      TS1005: ',' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1485,44)
      TS1068: Unexpected token. A constructor, method, accessor, or property was expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1485,57)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1485,65)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1485,66)
      TS1109: Expression expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1485,67)
      TS1109: Expression expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1490,17)
      TS1005: ',' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1490,26)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1494,17)
      TS1005: ',' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1494,26)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1498,15)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1498,41)
      TS1005: '(' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1504,17)
      TS1005: ',' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1504,32)
      TS1005: ',' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1504,41)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1504,47)
      TS1109: Expression expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1508,17)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1508,43)
      TS1005: '(' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1512,26)
      TS1005: ';' expected.

ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts
[tsl] ERROR in /home/parvez/Documents/cph-submit/node_modules/@types/node/ts4.8/util.d.ts(1514,1)
      TS1128: Declaration or statement expected.

webpack 5.75.0 compiled with 20 errors in 1931 ms
`

**Comment by qwedc001** [comment]
Any ideas on this issue? Really need this.

**Comment by urparvezali** [comment]
@qwedc001
here you can get the solution
https://github.com/urparvezali/cph-submit
